### ISSUE TITLE
Making a backup

### ISSUE THREAD

**Issue by xskrasek** [passbolt/charts-passbolt#12]
Hello, I want to ask whether you are considering building some functionality for backing up the deployment data or creating some backup guide for the Helm chart? Or do you consider it the responsibility of the underlying Kubernetes cluster to manage the data properly?

**Comment by dlen** [comment]
Hi @xskrasek!

We have no plans at the moment to bake backup functionality on the helm chart itself so it would be the responsibility of the admin.
However, I'm curious about what would you expect of such functionality. Let's say we build a k8s cron job that creates a backup of the passbolt database and stores it in a configured volume/s3/other locations? What kind of storage should this functionality support?

With a little bit more information we could think about making this happen.

**Comment by xskrasek** [comment]
Hello, 
To be honest, I do not have a clear vision yet; I just wanted to make sure I was not inventing the wheel :) Yes, I was thinking of some crone that would make copies of the database or the Kubernetes file systems and be capable of moving them elsewhere. 

Something like duplicity or restic could be used, as these seem to support multiple remote solutions to store backups.

**Comment by dlen** [comment]
Thanks for your feedback @xskrasek !!

At the moment we are not planning to add this process to the chart and for the checklist we will create a new section on https://help.passbolt.com/hosting/backup that shows how to backup in the case of a helm install
