### ISSUE TITLE
Problem with deployment on rootless containers

### ISSUE THREAD

**Issue by xskrasek** [passbolt/charts-passbolt#13]
Hello,
I am having trouble with deployment when using the non-root containers. In the deployment template, there is the init container that is using ./defaultsfile.cnf. However, in my case, I get an error that the file can not be created, which then causes the database check to fail because it loads without the configuration. 

I worked around it by providing the config as command parameters, but I wanted to check whether this is a real issue or something with my setup.

**Comment by dlen** [comment]
Yeah you are right! Rootless images won't be able to write on the /defaultsfile.cnf. This is a bug indeed, we will need to switch the location of this file to provide support for rootless images.
