### ISSUE TITLE
Missleading configuration in Mariadb secondary persistence

### ISSUE THREAD

**Issue by MTSym** [passbolt/charts-passbolt#14]
According to https://github.com/passbolt/charts-passbolt/blob/main/values.yaml#L71 there should be a "existingClaim" property for the secondary persistence configuration while the bitnami repository does not have such a property: https://github.com/bitnami/charts/tree/main/bitnami/mariadb

Also when trying to set the property I observed that it always created a custom PVC inside my cluster.

**Comment by dlen** [comment]
Thanks for the report @MTSym!! Looks like you are right https://github.com/bitnami/charts/issues/13962 we can remove this from the values for now.
