### ISSUE TITLE
Version 0.3.2 not available with "repo update"

### ISSUE THREAD

**Issue by MTSym** [passbolt/charts-passbolt#20]
It seems that the new `0.3.2` version was not correctly added to `https://download.passbolt.com/charts/passbolt/index.yaml`

Or am I missing something?

**Comment by dlen** [comment]
Should be fixed now. We got bitten by this one https://github.com/hayorov/helm-gcs/issues/191

**Comment by dlen** [comment]
Thanks for the report @MTSym !!
