### ISSUE TITLE
Volumes documentation inconsistency

### ISSUE THREAD

**Issue by it-svit** [passbolt/charts-passbolt#23]
## what
* documentation says that `/usr/share/php/passbolt/webroot/img/public/images` should be the volume
* But migrations refer to the `/usr/share/php/passbolt/webroot/img/public/Avatar`
* There might be an inconsistency between documentation and the code

## migrations

```
2023-05-29 15:49:20 error: The avatar with file Avatar/8a/d0/84/75a0d13b51e441f8a1e952bd996f4f5c/75a0d13b51e441f8a1e952bd996f4f5c.jpg could not be saved.
2023-05-29 15:49:20 warning: fopen(/usr/share/php/passbolt/webroot/img/public/Avatar/96/f0/d7/83e3ad5acda74fcdabec8af68e32d250/83e3ad5acda74fcdabec8af68e32d250.jpg): failed to open stream: No such file or directory
warning: 2 :: fopen(/usr/share/php/passbolt/webroot/img/public/Avatar/96/f0/d7/83e3ad5acda74fcdabec8af68e32d250/83e3ad5acda74fcdabec8af68e32d250.jpg): failed to open stream: No such file or directory on line 326 of /usr/share/php/passbolt/vendor/laminas/laminas-diactoros/src/Stream.php
```

## found during
https://github.com/passbolt/charts-passbolt/pull/22

**Comment by dlen** [comment]
Hi! @it-svit,

As of passbolt 3.2 avatars are not stored in the disk anymore. Image avatars are now stored in the database and copied to the disk as a cache mechanism. (https://help.passbolt.com/releases/pro/la-cle-des-champs https://help.passbolt.com/releases/ce/la-cle-des-champs)

If I understand it well you see these errors while building PR #22  which as per the way we store avatars would not be required and should be closed.

We will update the docker readme to point that the avatars volume is not required.

**Comment by dlen** [comment]
Regarding the use of passbolt.php we indeed do not provide in the chart a way to inject such file in the deployment. I think the best would be for it to be a secret.

I'm not sure if many people would like to inject the whole passbolt.php configuration file manually. I will keep this open to measure traction on such feature.

**Comment by dlen** [comment]
Sorry for the late reply.
I don't remember exactly the process to migrate avatars to the database but it would make sense that the avatars are available during that particular migration. Sadly we are not going to provide support to passbolt versions that old, you would need to do the upgrade out of band to then use the chart.

Thanks in any case to all your contributions!
