### ISSUE TITLE
Broken link https://www.passbolt.com/help/legal/cla

### ISSUE THREAD

**Issue by it-svit** [passbolt/charts-passbolt#24]
It wants me to sign [CLA for passbolt/charts-passbolt](https://cla-assistant.io/passbolt/charts-passbolt?pullRequest=22) and refers to https://www.passbolt.com/help/legal/cla.

But https://www.passbolt.com/help/legal/cla responds with `404`.

**Comment by dlen** [comment]
The link should be updated, let us know if it works for you

**Comment by it-svit** [comment]
Thanks! It works.
