### ISSUE TITLE
Setup SSL certificate for service

### ISSUE THREAD

**Issue by dmouha-xelians** [passbolt/charts-passbolt#28]
Hello,
I used the helm and chart to deploy Passbolt but I cannot find in the documentation where to override the nginx SSL certificate.

I checked the deployment and the pod, I saw that the certificate used are `/etc/ssl/certs/certificate.crt` and `/etc/ssl/certs/certificate.key`. 
In the deployment template there is a variable `extraVolumes` to mount additional config map. But there is nowhere to perform the volumeMount to mount the secret to the path of the certificates.
Can you please help by adding the extraVolumeMount or provide documentation on how to add our own certificate to the chart.

Thanks

**Comment by dlen** [comment]
Hi, would this be related with https://github.com/passbolt/charts-passbolt/pull/25 ?

I'm not sure to follow what you are missing that is not provided in that PR

**Comment by dlen** [comment]
Closing this one as a workaround has been provided already, feel free to reopen with more information.
