### ISSUE TITLE
Missing value used in deployment.yaml

### ISSUE THREAD

**Issue by xskrasek** [passbolt/charts-passbolt#29]
Hello, 

There is this value on line 137 in deployment yaml.             

`{{- toYaml .Values.redisProxyResources | nindent 12 }}`

The value is not defined in the values.yaml file. Is this intentional?

**Comment by dlen** [comment]
Hey thanks for the heads up! This is totally not intentional. 

Not sure what would be more  ergonomic:
 
``` .Values.app.cache.redis.sentinelProxy.resources```
Or 
```.Values.app.resources.redisProxy```
