### ISSUE TITLE
Newer MariaDB versions do not have mysql command

### ISSUE THREAD

**Issue by xskrasek** [passbolt/charts-passbolt#31]
Hello, I ran into issues with the mysql command used with the Mariadb init container in deployment. 

It might be possible to use mariadb command instead and mariadb-dump for doing backups. 

I had a bit of a hard time finding out why this happened and how to resolve this, so I want to let you know here in case it helps anyone else.

**Comment by dlen** [comment]
Hi @xskrasek ,

This has been reported in #26 and a work around has been provided in 0.3.3 https://github.com/passbolt/charts-passbolt/blob/0.3.3/CHANGELOG.md#033---2023-06-15

We provide defaults in the values.yml to use a different client application on init images.
I'm closing this issue, feel free to reopen it if the fixes provided in 0.3.3 are not working for you.
