### ISSUE TITLE
Helm charts generating incorrect jwt key and pem

### ISSUE THREAD

**Issue by SamuelColacchia** [passbolt/charts-passbolt#33]
Here is a link to the [forum post ](https://community.passbolt.com/t/passbolt-helm-chart-issue-with-ios-app/7992/2) discussing the issue 

In short it appear that when you let the helm charts generate a jwt key the pem does not match it. This results in the ios app being unable to validate the server.

**Comment by dlen** [comment]
Hi @SamuelColacchia 

Thanks for the heads up, indeed the public key is incorrect this will be fixed in the next version. In the meantime users would need to create their own jwt keys as described in the community post
