### ISSUE TITLE
disable nginx listening on ipv6 protocol

### ISSUE THREAD

**Issue by jouve** [passbolt/charts-passbolt#35]
I deploy passbold to a k8s cluster without ipv6 support.

I suggest patching the args of the main container :
```
          command:
            - "/bin/bash"
          args:
            - "-c"
            - |
              set -e
              > /etc/supervisor/conf.d/cron.conf
              if [ -z "$(ip -6 addr)" ]; then sed -i "/listen \[\:\:\]/d" /etc/nginx/sites-enabled/nginx-passbolt.conf /etc/nginx/snippets/passbolt-ssl.conf; fi
              /docker-entrypoint.sh
```

**Comment by dlen** [comment]
Hi @jouve, 

As proposed here https://github.com/passbolt/passbolt_docker/issues/193#issuecomment-1470855352 you can mount your custom nginx configuration on the container.

It is unlikely that we include such patches in the container or the chart for ipv6 when just mounting your specific nginx config would suffice.

**Comment by jouve** [comment]
it's not very user-friendly to shift the work to keep the conf. in sync to the user
