### ISSUE TITLE
passbolt throwing unexpected error

### ISSUE THREAD

**Issue by kvdheeraj-wmh** [passbolt/charts-passbolt#38]
I have installed passbolt using helm and imported the passwords. only 72/82 passwords were imported and the error for rest of them are "message": "Cannot import resource". I have ignored it and created those entries manually. 
when i want to share the 72 entries all at once with a group the page gets struck and i have to refresh, so i have to share 15 entries at a time. 

When adding a user to an existing group, Passbolt goes through the process of decrypting all the password envelopes and updating the group as expected. However, when it gets to the final stage (Updating the Group), it will hang at 100% for some time until a server error is received

I have followed the below link to setup passbolt HA 
https://blog.passbolt.com/installing-passbolt-with-helm-f9b685016c67

Tried: I`ve add a line in nginx as client_max_body_size 10M; and reloaded the nginx - no change in behavior 

EKS version : 1.26
helm Version:"v3.11.0
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-passbolt     default         1               2023-07-28 16:15:00.307224 -0400 EDT    deployed        passbolt-0.4.0  4.0.2-2-ce

![passbolt-error](https://github.com/passbolt/charts-passbolt/assets/104635070/7a317caa-fc58-428a-ab59-a7a0a5f7b08d)

**Comment by dlen** [comment]
Do you have any logs from the passbolt deployment the moment you experienced the error?

**Comment by kvdheeraj-wmh** [comment]
i checked the nginx logs and passbolt logs. logs are not getting updated. The log files are created on Jul and no logs got updated.  is there a place in values.yaml i can enable debug logs ?

**Comment by kvdheeraj-wmh** [comment]
I see these logs around the same time on std output 
2023-08-02 12:27:13,662 INFO reaped unknown pid 36336 (exit status 0)
2023-08-02 12:27:13,662 INFO reaped unknown pid 36337 (exit status 0)
2023-08-02 12:27:13,662 INFO reaped unknown pid 36338 (exit status 0)
2023-08-02 12:27:13,662 INFO reaped unknown pid 36342 (exit status 0)
2023-08-02 12:27:13,662 INFO reaped unknown pid 36343 (exit status 0)
2023-08-02 12:27:13,662 INFO reaped unknown pid 36344 (exit status 0)

**Comment by kvdheeraj-wmh** [comment]
Hello Dlen, 

i checked php config 
cat /etc/php/8.2/fpm/php-fpm.conf
;;;;;;;;;;;;;;;;;;;;;
; FPM Configuration ;
;;;;;;;;;;;;;;;;;;;;;

; All relative paths in this configuration file are relative to PHP's install
; prefix (/usr). This prefix can be dynamically changed by using the
; '-p' argument from the command line.

;;;;;;;;;;;;;;;;;;
; Global Options ;
;;;;;;;;;;;;;;;;;;

[global]
; Pid file
; Note: the default prefix is /var
; Default Value: none
; Warning: if you change the value here, you need to modify systemd
; service PIDFile= setting to match the value here.
pid = /run/php/php8.2-fpm.pid

; Error log file
; If it's set to "syslog", log is sent to syslogd instead of being written
; into a local file.
; Note: the default prefix is /var
; Default Value: log/php-fpm.log
error_log = /var/log/php8.2-fpm.log

; syslog_facility is used to specify what type of program is logging the
; message. This lets syslogd specify that messages from different facilities
; will be handled differently.
; See syslog(3) for possible values (ex daemon equiv LOG_DAEMON)
; Default Value: daemon
;syslog.facility = daemon

; syslog_ident is prepended to every message. If you have multiple FPM
; instances running on the same server, you can change the default value
; which must suit common needs.
; Default Value: php-fpm
;syslog.ident = php-fpm

; Log level
; Possible Values: alert, error, warning, notice, debug
; Default Value: notice
;log_level = notice

; Log limit on number of characters in the single line (log entry). If the
; line is over the limit, it is wrapped on multiple lines. The limit is for
; all logged characters including message prefix and suffix if present. However
; the new line character does not count into it as it is present only when
; logging to a file descriptor. It means the new line character is not present
; when logging to syslog.
; Default Value: 1024
;log_limit = 4096

; Log buffering specifies if the log line is buffered which means that the
; line is written in a single write operation. If the value is false, then the
; data is written directly into the file descriptor. It is an experimental
; option that can potentially improve logging performance and memory usage
; for some heavy logging scenarios. This option is ignored if logging to syslog
; as it has to be always buffered.
; Default value: yes
;log_buffering = no

; If this number of child processes exit with SIGSEGV or SIGBUS within the time
; interval set by emergency_restart_interval then FPM will restart. A value
; of '0' means 'Off'.
; Default Value: 0
;emergency_restart_threshold = 0

; Interval of time used by emergency_restart_interval to determine when
; a graceful restart will be initiated.  This can be useful to work around
; accidental corruptions in an accelerator's shared memory.
; Available Units: s(econds), m(inutes), h(ours), or d(ays)
; Default Unit: seconds
; Default Value: 0
;emergency_restart_interval = 0

; Time limit for child processes to wait for a reaction on signals from master.
; Available units: s(econds), m(inutes), h(ours), or d(ays)
; Default Unit: seconds
; Default Value: 0
;process_control_timeout = 0

; The maximum number of processes FPM will fork. This has been designed to control
; the global number of processes when using dynamic PM within a lot of pools.
; Use it with caution.
; Note: A value of 0 indicates no limit
; Default Value: 0
; process.max = 128

; Specify the nice(2) priority to apply to the master process (only if set)
; The value can vary from -19 (highest priority) to 20 (lowest priority)
; Note: - It will only work if the FPM master process is launched as root
;       - The pool process will inherit the master process priority
;         unless specified otherwise
; Default Value: no set
; process.priority = -19

; Send FPM to background. Set to 'no' to keep FPM in foreground for debugging.
; Default Value: yes
;daemonize = yes

; Set open file descriptor rlimit for the master process.
; Default Value: system defined value
;rlimit_files = 1024

; Set max core size rlimit for the master process.
; Possible Values: 'unlimited' or an integer greater or equal to 0
; Default Value: system defined value
;rlimit_core = 0

; Specify the event mechanism FPM will use. The following is available:
; - select     (any POSIX os)
; - poll       (any POSIX os)
; - epoll      (linux >= 2.5.44)
; - kqueue     (FreeBSD >= 4.1, OpenBSD >= 2.9, NetBSD >= 2.0)
; - /dev/poll  (Solaris >= 7)
; - port       (Solaris >= 10)
; Default Value: not set (auto detection)
;events.mechanism = epoll

; When FPM is built with systemd integration, specify the interval,
; in seconds, between health report notification to systemd.
; Set to 0 to disable.
; Available Units: s(econds), m(inutes), h(ours)
; Default Unit: seconds
; Default value: 10
;systemd_interval = 10

;;;;;;;;;;;;;;;;;;;;
; Pool Definitions ;
;;;;;;;;;;;;;;;;;;;;

; Multiple pools of child processes may be started with different listening
; ports and different management options.  The name of the pool will be
; used in logs and stats. There is no limitation on the number of pools which
; FPM can handle. Your system will tell you anyway :)

; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /usr otherwise
include=/etc/php/8.2/fpm/pool.d/*.conf

ls -l /var/log/php8.2-fpm.log
lrwxrwxrwx 1 root root 11 Jun 15 08:18 /var/log/php8.2-fpm.log -> /dev/stderr


root@my-passbolt-depl-srv-758649579f-bn2dv:/etc/nginx# cat nginx.conf 
user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##
        client_max_body_size 10M;

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}


when you mean recreate the issue create new passbolt using helm and recreate the issue ?
I see the lines for error log for php and nginx which are creating log files but no logs in there. 
values.yaml doesnt have an option to set log level. 
I am trying to enable debug logs , please help !

**Comment by dlen** [comment]
when you mean recreate the issue create new passbolt using helm and recreate the issue ? -> Yes
I see the lines for error log for php and nginx which are creating log files but no logs in there. -> https://github.com/passbolt/passbolt_docker/blob/master/debian/Dockerfile#L40 all log files are redirected to stdout that is why you don't find anything in the log files.

**Comment by stripthis** [comment]
Closing as stale, if you are still encountering an issue with your install, you can open a thread on the community forum: https://community.passbolt.com
