### ISSUE TITLE
Bitnami dependency

### ISSUE THREAD

**Issue by samip5** [passbolt/charts-passbolt#4]
I would like to point out that their images are as closed-source as possible, which has multiple issues:

- Not able to update their workflows so that multi-arch images are possible
- Not able to compile their images on your own

I would urge to not depend on their charts/images as a result.

They have also recently removed a lot of their charts from the index out of nowhere (`https://github.com/bitnami/charts/issues/10833`) and they don't have multi-arch images of anything (https://github.com/bitnami/charts/issues/7305)

**Comment by dlen** [comment]
Hi @samip5 thanks for the information,

We provide the charts as a way to make it easy to run passbolt in Kubernetes. You could run your own mariadb and redis if you want. In any case, if you have a suggestion regarding a mariadb and/or redis helm chart to use as a dependency we will be happy to consider it.

**Comment by samip5** [comment]
Bitnami seem to have added multi-arch images, so at least that portion doesn't apply anymore.
Unfortunately, there is not many choices for dependency charts to use. :(

**Comment by dlen** [comment]
That is some good news! We will keep the dependencies as they are now until a new option appears that suits more the community needs-

 I will close this issue but thanks a lot for your feedback it is greatly appreciated! Of course feel free to re-open the issue if you find an option that you think it is suitable so we can discuss it.
