### ISSUE TITLE
Passbolt integration with external database which is hosted on cloud as managed MariaDB service

### ISSUE THREAD

**Issue by Babug01** [passbolt/charts-passbolt#43]
Hi all,

Is there any possibility to connect passbolt with external database which is hosted in any cloud as managed service?

If yes, please share me the steps for integration,

I'm unable to found the exact steps to configure passbolt with cloud managed mariadb service.

**Requirement:**
Need to integrate passbolt with azure hosted MariaDB managed instance

**Comment by dlen** [comment]
Hello @Babug01 

Use our community forum for more installation tips and tricks https://community.passbolt.com
