### ISSUE TITLE
PASSBOLT_SSL_FORCE set to false, still redirecting to HTTPs

### ISSUE THREAD

**Issue by debugger24** [passbolt/charts-passbolt#45]
Setting `PASSBOLT_SSL_FORCE` to false is not enough to run in without TLS, the passbolt server still redirecting me to https website.

In my current setup, I am using TLS termination at my ingress and non TLS traffic b/w ingress and passbolt as of now, but it doesn't seem to be working. I am hitting `https://passbolt.local` but passbolt see it as non HTTPs traffic and redirects to `https://passbolt.local`, so kind of stuck in infinite loop resulting in too many redirects.

I think it is somewhere implemented in `passbolt-library`. From where can I access passbolt-library ?

**Comment by dlen** [comment]
Hello if you could bring some more info we might be able to help you. In any case we plan to publish the passbolt-library soon.

**Comment by RobertInAms** [comment]
A summing you set up your hosts file, you could try this

passboltEnv:
  plain:
    APP_FULL_BASE_URL: "http://passbolt.local"

**Comment by dlen** [comment]
Closing as stale, feel free to reopen if needed

**Comment by dlen** [comment]
A fix has been shipped as part of 1.3.3!
