### ISSUE TITLE
passbolt-depl-srv in CrashLoopBackOff

### ISSUE THREAD

**Issue by Joao-1** [passbolt/charts-passbolt#46]
Hello!

I'm trying to install the chart following the [official guide](https://help.passbolt.com/hosting/install/ce/helm.html), but I am getting the following error in the passbolt-depl-srv pod:
![image](https://github.com/passbolt/charts-passbolt/assets/58475277/c955d737-7af1-445a-8c29-374765967a70)

All redis and mariadb pods is running.

Any suggestions of what it could be?

**Comment by dlen** [comment]
Hello @Joao-1 please use the [community forum](https://community.passbolt.com) for more help installing this chart.

Thanks!
