### ISSUE TITLE
error in deployment.yaml (imagePullPolicy)

### ISSUE THREAD

**Issue by op-euga** [passbolt/charts-passbolt#52]
imagePullPolicy: .Values.app.image.pullPolicy
missing {{}}
should be 
imagePullPolicy: {{ .Values.app.image.pullPolicy }}

in the main container.

**Comment by dlen** [comment]
Thanks for the report! We'll do a hotfix today!

**Comment by op-euga** [comment]
You're welcome. thx for the quick response and fix.

**Comment by dlen** [comment]
This should have been fixed in 0.4.4. 

Thanks again for the heads up!
