### ISSUE TITLE
Deploying with postgres db

### ISSUE THREAD

**Issue by arbianqx** [passbolt/charts-passbolt#55]
Hi there,

Is there any chance to deploy this with postgres database.

I tried to change the client to (psql) and also specify the secrets for the database connection but it gets stuck on Init container.

Is there any workaround?

**Comment by arbianqx** [comment]
Also tried with an external Mariadb instance on aws but it seems to not work either

**Comment by dlen** [comment]
Hey @arbianqx,

You are right the chart lacks proper postgresql support in the init container. An option to disable the init container from values would also be useful.

Only workaround that comes to my mind now would be to clone the chart and remove or disable the initContainer from the deployment template if your postgresql is available.

**Comment by dlen** [comment]
No problem! 

DATASOURCES_DEFAULT_SCHEMA if you want to specify postgresql schema

**Comment by arbianqx** [comment]
Well that actually didn't work either.

I went to docker-compose and check the configuration there.

DATASOURCES_DEFAULT_DRIVER: Cake\Database\Driver\Postgres
DATASOURCES_DEFAULT_ENCODING: "utf8"
DATASOURCES_DEFAULT_URL: "postgres://passbolt:P4ssb0lt@db:5432/passbolt?schema=passbolt"

I made sure to add the environment variables in this format. The migrations applied.

Now I'm gonna check to create a ingress and such and to see if its working.

Will keep you posted.

**Comment by xskrasek** [comment]
Will support for Postgres in the helm chart be implemented in the foreseeable future? It is a desirable future, and we do not want to modify the chart if possible, to ease the update process.

**Comment by dlen** [comment]
Yeah we want to tackle this as the next item for the chart. However, I can't give you an ETA at the moment as we have limited bandwidth.

**Comment by dlen** [comment]
Fixed with 0.5 release
