### ISSUE TITLE
different secrets for internal & external tls

### ISSUE THREAD

**Issue by jouve** [passbolt/charts-passbolt#69]
when exposing passbolt using an ingress, there are 2 http hops :
- browser -> ingress: it uses a "public" certificate valid for the public DNS passbolt.example.com 
- ingress -> passbolt: it reuse the certificate from above, but it should use a different certificate valid for the service name `{{ .Release.Name }}.{{ .Release.Namespace }}.svc` 

so I guess the chart should expose 2 different values

**Comment by dlen** [comment]
Added in 1.0.0
