### ISSUE TITLE
Issues with running rootless containers.

### ISSUE THREAD

**Issue by xskrasek** [passbolt/charts-passbolt#7]
Hello, I am trying to use this chart with kubernetes cluster, that needs to run as non-Root.

However, if I understand it correctly, the container has to run 

```              
apt-get update;
apt-get install -y php-redis;
```
Which does not work on the rootless container. I also encountered some other issues, but I am still trying to figure out, if they can be resolved by changes to the configuration, or if they need to be handled by the image as well.

**Comment by dlen** [comment]
Yes you are right! Thanks we will make this php extension part of the passbolt debian packages to make new rootless images usable on this chart!

**Comment by dlen** [comment]
We have added php-redis as part of the dependencies of the passbolt packages and removed the installation of the extension from the chart deployment. That should do the trick to run rootless images. 

Only requirement is to use passbolt docker image >= 3.12.0-3

Thanks for your feedback!!!
