### ISSUE TITLE
Passbolt installation fail

### ISSUE THREAD

**Issue by vintury** [passbolt/charts-passbolt#8]
I try to install passbolt on clear namespace in k8s cluster. But have error:

➜  ~ helm repo add passbolt "https://download.passbolt.com/charts/passbolt"
"passbolt" has been added to your repositories
➜  ~ helm install mypassbolt passbolt/passbolt
Error: INSTALLATION FAILED: failed pre-install: unable to build kubernetes object for pre-install hook passbolt/templates/configmap-env.yaml: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.EMAIL_TRANSPORT_DEFAULT_HOST

**Comment by Tecnobutrul** [comment]
Hi vintury. I've tried to reproduce it without success. Which helm version are you running?
