### ISSUE TITLE
Chart version 1.1.1 installation failure

### ISSUE THREAD

**Issue by jaredpatrick37** [passbolt/charts-passbolt#85]
Chart repo:  
```
https://download.passbolt.com/charts/passbolt
```

Install command:
```
helm install passbolt passbolt/passbolt -n passbolt --version 1.1.1
```

I am getting the following error when installing version 1.1.1:
```
Error: INSTALLATION FAILED: template: passbolt/templates/tests/rolebind.yaml:1:45: executing "passbolt/templates/tests/rolebind.yaml" at <.Values.integrationTests.enabled>: nil pointer evaluating interface {}.enabled
```

I resolved this issue by running the helm install with the following --set:
```
helm install passbolt passbolt/passbolt -n passbolt --version 1.1.1 --set integrationTests.enabled=false
```

The `integrationTests` value is not defined in the [values.yaml](https://github.com/passbolt/charts-passbolt/blob/1.1.1/values.yaml), so there probably needs to be a `default false` [here](https://github.com/passbolt/charts-passbolt/blob/1.1.1/templates/tests/rolebind.yaml#L1)

**Comment by dlen** [comment]
Hey @jaredpatrick37 thanks for the report. 
I'm unable to reproduce the issue, which version of helm are you using?

**Comment by dlen** [comment]
Close as stale
